### ISSUE TITLE
pod structure support

### ISSUE THREAD

**Issue by berdof** [mattma/ember-rocks#14]
What about a pod structure support like in ember-cli? It is very useful especially when project is large.

**Comment by mattma** [comment]
@berdof I actually use the Pod structure myself. and I love it. It makes sense to group component scripts and template together in one folder.

If you look at the repo commits history, I did not have any recent activity.

Here is the reason, 

I talked to [@stefanpenner](https://github.com/stefanpenner), the creator of Ember-CLI several times at Ember meetup. We exchanged our ideas on build pipeline for Ember ecosystem. It turns out that we do not need multiple build system, and we need an unity. Ember-Cli will be the ONLY official build system for Ember project onward, and it is maintained by Ember core team.

I am currently using Ember-Cli for all of my Ember projects, and I love it. Big shout out to CLI team. You should consider to use Ember-cli. Only reference this repo for your learning purpose.
